CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  varchar(255)   NOT NULL,
    email varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    item_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar,
    description varchar,
    available   boolean,
    owner       BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    request     BIGINT
);

CREATE TABLE IF NOT EXISTS booking
(
    booking_id BIGINT
);